server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:postgresql://dpg-d4fkhtemcj7s73aq0le0-a.frankfurt-postgres.render.com:5432/bdcamisa_vodn
    username: tienda_user
    password: 51K6BX9Dhx7vj4xk0t7qodNPXPuhLsgz
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false   # <-- MUY IMPORTANTE para acelerar el arranque
  datasource.hikari:
    maximum-pool-size: 2  # Render free es muy limitado

  flyway:
    enabled: false
    validate-on-migrate: false   # <-- evita validaciones que tardan 1-2 minutos
    baseline-on-migrate: true    # <-- arranque rÃ¡pido
