server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:postgresql://dpg-d4fkhtemcj7s73aq0le0-a.frankfurt-postgres.render.com:5432/bdcamisa_vodn
    username: tienda_user
    password: 51K6BX9Dhx7vj4xk0t7qodNPXPuhLsgz
  jpa:
    hibernate:
      ddl-auto: validate       # Solo valida que las tablas existan
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true  # Considera la BD existente como base
    locations: classpath:db/migration  # Ruta de tus scripts SQL

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
